### ISSUE TITLE
Cards disappeared after toggling modes

### ISSUE THREAD

**Issue by jc00ke** [lfph/lfph-landscape#74]
In Firefox 85.0 on Ubuntu 20.10, I switched from `Landscape` to `Card Mode` back to `Landscape` and the cards disappeared. I didn't see any JS errors in console and I was unable to get the cards to come back with soft or hard refreshes.

![image](https://user-images.githubusercontent.com/18191/106915906-70a96800-66bb-11eb-9eea-be88596e35a4.png)

**Comment by jennydove** [comment]
@jc00ke I submitted this issue to the upstream app, as they're probably the ones who can actually dig in on this and it is unlikely to be unique to LFPH. Issue here: https://github.com/cncf/landscapeapp/issues/701

I'm going to close this one.
